### ISSUE TITLE
Enable REDIS_READY_PATTERN to be configurable

### ISSUE THREAD

**Issue by xhoong** [fmonniot/embedded-redis#10]
Hi, I'm using Redis 4.0.8 and the startup message do not contains the sentence stated in REDIS_READY_PATTERN `".*The server is now ready to accept connections on port.*"`. Is there a way to make this as configurable? Since it is now encourage to bundle your own binary.

Thanks.

**Comment by fmonniot** [comment]
Hello,
I guess `RedisServer` and `RedisSentinel` could take an optional `Pattern` to use, instead of the default one (a bit like it's done for the port).
That being said, I don't really have time to work on it so feel free to open a PR for it :)

Thanks

**Comment by xhoong** [comment]
PR #11 submitted. I think it would be good to have the exec provider maintaining the exec and the pattern. Also the RedisServer and RedisSentinel has public interface to override the pattern (for pre-installed REDIS). Even though for pre-installed REDIS, I think user should always define their own ExecProvider and set the provider in Redis Builder.

**Comment by fmonniot** [comment]
Fixed via #11

**Comment by fmonniot** [comment]
I released version 1.6.0 on bintray. Enjoy.

**Comment by xhoong** [comment]
@fmonniot THANKS! Great of you to keep this project alive!!
